#
# Based on sample from: https://github.com/spring-cloud-samples/configserver/blob/master/src/main/resources/application.yml
#

server:
  port: 8888

management:
  context_path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
  client:
    serviceUrl:
      defaultZone: ${vcap.services.my-service-registry.credentials.uri:http://127.0.0.1:8761}/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jshingler/config-repo

---
spring:
  profiles: cloud

eureka:
#  password: password
  instance:
    hostname: ${vcap.application.uris[0]}
#    hostname: jsconfigserver.cfapps.io
    nonSecurePort: 80